afritec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('root/', include('root.urls', namespace = 'root')),
    path('', include('root.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views


app_name = 'root'

urlpatterns =[
path('', views.index, name = 'index'),
path('register/', views.register_view, name = 'register'),
path('login/', views.login_view, name = 'login'),
path('logout/', views.logout_view, name = 'logout'),

path('dashboard/', views.home, name = 'dashboard'),
path('make_complaint/', views.make_complaint,name='make_complaint'),
path('complaint_history/', views.complaint_history,name='complaint_history'),
path('orders/', views.orders, name = 'my_orders'),

path('dealers/', views.shop_list, name = 'dealers'),
path('store/', views.itemstore, name = 'store'),
path('contacts/', views.contacts, name = 'contacts'),
path('about/', views.about, name = 'about'),
path('cart/', views.cart, name="cart"),
path('checkout/', views.checkout, name="checkout"),
path('update_item/', views.updateItem, name="update_item"),
path('process_order/',views.processOrder, name="process_order"),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

root/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Shop(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    description = models.CharField(max_length=250)
   
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null = True, blank=True)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    # Below property tells, that if no image is uploaded,
	# it will show broken image picture
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)
    
    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            # if, a product is not digital, then it has to be shipped
            if i.product.digital == False:
                shipping = True
                return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.address

class Complaint(models.Model):
    customer= models.ForeignKey(User, on_delete=models.CASCADE)
    description =models.CharField(max_length=500)
    admin_comment=models.CharField(max_length=200,default='Nothing')
    asked_date =models.DateField(auto_now=True)
    def __str__(self):
        return self.description

root/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 

#create admin
class CreateAdminForm(forms.Form):
    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']

#register a user
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model=User
        fields=['first_name','last_name','username','email','password1','password2',]

class OrderForm(forms.ModelForm): 
    class Meta:
        model = models.OrderItem
        fields = ['product','order','quantity']

class ComplaintForm(forms.ModelForm):
    class Meta:
        model=models.Complaint
        fields=['description']
        widgets = {
        'description': forms.Textarea(attrs={'rows': 6, 'cols': 30})
        }

root/views.py
from django.shortcuts import render, redirect
from . models import *
from .forms import UserRegistrationForm, ComplaintForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, HttpResponseRedirect
from .decorators import unauthenticated_user
from django.contrib.auth.decorators import login_required
from .forms import *
from .utils import cookieCart, cartData, guestOrder
from django.http import JsonResponse
import datetime
import json
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    data = cartData(request)
    cartItems = data['cartItems']
        
    products = Product.objects.all()
    context = {"products":products, 'cartItems':cartItems}
    return render(request, 'root/store.html', context)

@login_required(login_url='/login')
def home(request):
    data = cartData(request)
    cartItems = data['cartItems']
        
    products = Product.objects.all()
    dict={
        "products":products, 'cartItems':cartItems,
        'customer':User.objects.get(id=request.user.id),
        'available_products':Product.objects.all().count(),
        'orders_made':Order.objects.all().filter(customer=User.objects.get(id=request.user.id)).count(),
        'total_complaints':Complaint.objects.all().filter(customer=User.objects.get(id=request.user.id)).count(),
    }
    return render(request,'root/dashboard.html', context=dict)

@unauthenticated_user
def register_view(request):
    if request.method=='POST':
        form=UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.info(request, f"Dear {username}, Your account has been created.")
            return redirect('root:dashboard')
    else:
        form = UserRegistrationForm()
    return render(request,'root/register.html',{'form':form})


@unauthenticated_user    
def login_view(request):
    form = AuthenticationForm(request, data=request.POST)
    if request.method == "POST":
         if form.is_valid():
             username = form.cleaned_data.get('username')
             password = form.cleaned_data.get('password')
             user = authenticate(username=username, password=password)
             if user is not None:
                 login(request, user)
                 messages.info(request, f"You are now logged in as {username}.")
                 return redirect("root:dashboard")
             else:
                 messages.error(request,"Invalid username or password.")
         else:
             messages.error(request,"Invalid username or password.")
             form = AuthenticationForm()
    return render(request = request, template_name="root/login.html", context={"login_form":form})

@login_required(login_url='/login')
def logout_view(request):
    logout(request)
    messages.info(request,"Logged out successfully!")
    return redirect('root:login')


def shop_list(request):
    shops = Shop.objects.all()
    context = {'shops':shops}
    return render(request, 'root/dealers.html', context)

def itemstore(request):
    data = cartData(request)
    cartItems = data['cartItems']
        
    products = Product.objects.all()
    context = {"products":products, 'cartItems':cartItems}
    return render(request, 'root/store.html', context)

def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
                    
    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'root/cart.html', context)

 
def about(request):
    data  = cartData(request)
    cartItems = data['cartItems']

    products = Product.objects.all()
    context = {'products':products, 'cartItems':cartItems} 
    return render(request, 'root/about.html', context)



def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
        
    context = {'items':items, 'order':order, 'cartItems':cartItems, 'shipping':False}
    return render(request, 'root/checkout.html', context)

def contacts(request):
    data  = cartData(request)
    cartItems = data['cartItems']

    products = Product.objects.all()
    context = {'products':products, 'cartItems':cartItems}  
    return render(request, 'root/contacts.html', context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action :', action)
    print('Product :',productId)
    customer = request.user.id
    product = Product.objects.get(id=productId)
    # below line attaches the order to the given customer
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    # in the below line, we are using 'get_or_create' to change the values of orderItem, if it already exists
    # so, if it already exists, we don't want to create orderItem again, we just want to change the quantity of orderItem
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action =='add':
        # by clicking up arrow, increment orderItem by 1
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        # by clicking up arrow, decrement orderItem by 1
        orderItem.quantity = (orderItem.quantity - 1)

    # save quantity of products, for an order
    orderItem.save()

    if orderItem.quantity <= 0:
        # remove the orderItem from cart, when quantity reaches 0, or below it
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

#from django.views.decorators.csrf import csrf_exempt

#@csrf_exempt
def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.id
        order, created = Order.objects.get_or_create(customer_id=customer, complete=False)
       
    else:
        # guestOrder function is present in utils.py
        customer, order = guestOrder(request, data)
        
    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],
            )

    return JsonResponse("Payment submitted...",safe=False)

def make_complaint(request):
    customer = User.objects.get(id=request.user.id)
    complaintForm=ComplaintForm() 
    
    if request.method=='POST':
        complaintForm=ComplaintForm(request.POST)
        if complaintForm.is_valid():
            
            complaint = complaintForm.save(commit=False)
            complaint.customer=customer
            complaint.save()
            return redirect('root:complaint_history')
    return render(request,'root/make_complaint.html',{'complaintForm':complaintForm,'customer':customer})

def complaint_history(request):
    customer = User.objects.get(id=request.user.id)
    complaints = Complaint.objects.all().filter(customer=customer)
    return render(request,'root/complaint_history.html',{'complaints':complaints,'customer':customer})

def orders(request):
    customer = User.objects.get(id=request.user.id)
    orders = Order.objects.all().filter(customer=customer)
    return render(request,'root/my_orders.html',{'orders':orders,'customer':customer})

root/templates/root/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Afritec</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
	  <meta name="description" content="Afritec Store is a Demo Ecommerce website made with Django and Javascript. It has functionalities such as Add to cart, and PayPal Payment Integration">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'root/style.css' %}"/>
    <meta name = "viewport" content = "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
    <style type="text/css">    
    .bg-dark {
    background-color: #212529!important;
	}
    .navbar-brand {
		margin: -20px;
    }
  </style>
</head>

<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-end">
					<a href="/store" class="navbar-brand">
						<img  id="web-icon" src="{% static 'root/images/afritec.jfif' %}">
					</a>
					<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
						<span class="navbar-toggler-icon"></span>
					</button>
						<div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
							<div class="navbar-nav">
								<p style="padding-left: 15px;" class="nav-item nav-link active"></p>
								<a href="/store" class="nav-item nav-link">Store</a>
							</div>
							<div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
								<ul class="navbar-nav text-right">
									
									<li class="nav-item active">
										<a href="{% url 'root:about' %}" class="nav-item nav-link">About Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:contacts' %}" class="nav-item nav-link">Contact Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:login' %}">
											<img  id="cart-icon" src="{% static 'root/images/user.png' %}">
										</a>
									</li>
								</ul>
							</div>
				</nav>
        <section class="main-content bg-light py-4 mb-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="row mb-3">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h2>ABOUT US</h2>
                                        <hr>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12"></h2>
                                        <div class="row contact-fields">
                                            <p>This is an E-Commerce site where by one can buy items online
                                            and have them delivered to their door step or via email depending on the type of product one purchases
            
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>                                        
</body>
</html>

root/templates/root/contacts.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Afritec</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
	  <meta name="description" content="Afritec Store is a Demo Ecommerce website made with Django and Javascript. It has functionalities such as Add to cart, and PayPal Payment Integration">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'root/style.css' %}"/>
    <meta name = "viewport" content = "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
    <style type="text/css">    
    .bg-dark {
    background-color: #212529!important;
	}
    .navbar-brand {
		margin: -20px;
    }
  </style>
</head>

<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-end">
					<a href="/store" class="navbar-brand">
						<img  id="web-icon" src="{% static 'root/images/afritec.jfif' %}">
					</a>
					<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
						<span class="navbar-toggler-icon"></span>
					</button>
						<div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
							<div class="navbar-nav">
								<p style="padding-left: 15px;" class="nav-item nav-link active"></p>
								<a href="/store" class="nav-item nav-link">Store</a>
							</div>
							<div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
								<ul class="navbar-nav text-right">
									
									<li class="nav-item active">
										<a href="{% url 'root:about' %}" class="nav-item nav-link">About Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:contacts' %}" class="nav-item nav-link">Contact Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:login' %}">
											<img  id="cart-icon" src="{% static 'root/images/user.png' %}">
										</a>
									</li>
								</ul>
							</div>
				</nav>
<div class="container">
  <div class="contact-section">
    <h2 class="ct-section-head">CONTACT US</h2>
    <div class="row contact-fields">
      <div class="col-md-8 left-form">
       <form method="post" action="">
        <div class="form-group">
          <label class="sr-only" for="fname">First Name *</label>
          <input class="required form-control" id="fname" name="fname" placeholder="First Name&nbsp;*" type="text"  required>
        </div>
        <div class="form-group">
          <label class="sr-only" for="lname">Last Name *</label>
          <input class="required form-control" id="lname" name="lname" placeholder="Last Name&nbsp;*" type="text"  required>
        </div>
        <div class="form-group">
          <label class="sr-only" for="contactEmail">Email *</label>
          <input class="required form-control h5-email" id="contactEmail" name="contactEmail" placeholder="Email&nbsp;*" type="text"  required>
        </div>
        <div class="form-group">
          <label class="sr-only" for="contactPhone">Phone *</label>
          <input class="required form-control h5-phone" id="contactPhone" name="contactPhone" placeholder="Phone&nbsp;*" type="text"  required>
        </div>
        <div class="form-group">
          <label class="sr-only" for="comment">Type your message here</label>
          <textarea class="required form-control" id="comment" name="comment" placeholder="Type your message here&nbsp;*" rows="6" required></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>  
      </form>
      <div class="col-md-4 contact-info">
      <div class="phone">
        <h2>Call</h2>
        <a href="tel:+25452096397">0752096397</a>
      </div>
      <div class="email">
        <h2>Email</h2>
        <a href="mailto:info@afritec.com">info@afritec.com</a>
      </div>
      </div>
    </div>
    </div>
  </div>
</div>                                        
</body>
</html>

root/templates/root/dashboard.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} Dashboard {% endblock %}
{%load static%}
{% block body %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    
    <style type="text/css">

      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: none;
      }
  
      .bg-c-green {
        background:none;
      }
  
  
      .bg-c-pink {
        background: none;
      }
  
  
      .card {
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        border: 1px solid black;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 45px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
      left: 0px;
      right: 0px;
    }

    </style>
  </head>


  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xl-4">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20"> <a href="{% url 'root:store' %}" style="text-decoration: none;color:blue;font-weight:bold">Available Products</a> </h6>
            <h2 class="text-right" style="text-decoration: none;color:blue;font-weight:bold"><i  class="fab fa-product-hunt f-left"></i><span>{{available_products}}</span></h2>            
          </div>
        </div>
      </div>
  
      <div class="col-md-4 col-xl-4">
        <div class="card bg-c-green order-card">
          <div class="card-block">
            <h6 class="m-b-20"><a href="{% url 'root:my_orders' %}" style="text-decoration: none;color:green;font-weight:bold">Total Orders Made</a> </h6>
            <h2 class="text-right" style="text-decoration: none;color:green;font-weight:bold"><i class="fab fa-product-hunt f-left"></i><span>{{orders_made}}</span></h2>            
          </div>
        </div>
      </div>
  
      <div class="col-md-8 col-xl-4">
        <div class="card bg-c-pink order-card">
          <div class="card-block">
            <h6 class="m-b-30"><a href="{% url 'root:complaint_history' %}" style="text-decoration: none;color:black;font-weight:bold">My Complaints</a></h6>
            <h2 class="text-right" style="text-decoration: none;color:black;font-weight:bold"><i class="fas fa-question-circle f-left"></i><span>{{total_complaints}}</span></h2>            
          </div>
        </div>
      </div>
       
    </div>
  </div>


<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
{% endblock %}

root/templates/root/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Afritec</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
	  <meta name="description" content="Afritec Store is a Demo Ecommerce website made with Django and Javascript. It has functionalities such as Add to cart, and PayPal Payment Integration">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'root/style.css' %}"/>
    <meta name = "viewport" content = "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
	<style type="text/css">
    
    .bg-dark {
    background-color: #212529!important;
	}
    .navbar-brand {
		margin: -20px;
    }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-end">
					<a href="/store" class="navbar-brand">
						<img  id="web-icon" src="{% static 'root/images/afritec.jfif' %}">
					</a>
					<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
						<span class="navbar-toggler-icon"></span>
					</button>
						<div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
							<div class="navbar-nav">
								<p style="padding-left: 15px;" class="nav-item nav-link active"></p>
								<a href="/login" class="nav-item nav-link">Customer</a>          
          						<a href="/admin" class="nav-item nav-link">Admin</a>
							</div>
							<div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
								<ul class="navbar-nav text-right">
									
									<li class="nav-item active">
										<a href="{% url 'root:about' %}" class="nav-item nav-link">About Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:contacts' %}" class="nav-item nav-link">Contact Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:register' %}">
											<img  id="cart-icon" src="{% static 'root/images/user.png' %}">
										</a>
									</li>
								</ul>
							</div>
				</nav>
    {% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Forgot your password!<a href="/password_reset">Reset</a>.</p>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>
</div>
</body>
</html>
  

root/templates/root/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Afritec</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
	<meta name="description" content="Afritec Store is a Demo Ecommerce website made with Django and Javascript. It has functionalities such as Add to cart, and PayPal Payment Integration">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'root/style.css' %}"/>
    <meta name = "viewport" content = "width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
	<style type="text/css">
    
    .bg-dark {
    background-color: #212529!important;
	}
    .navbar-brand {
		margin: -20px;
    }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-end">
					<a href="/store" class="navbar-brand">
						<img  id="web-icon" src="{% static 'root/images/afritec.jfif' %}">
					</a>
					<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
						<span class="navbar-toggler-icon"></span>
					</button>
						<div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
							<div class="navbar-nav">
								<p style="padding-left: 15px;" class="nav-item nav-link active"></p>
								<a href="/login" class="nav-item nav-link">Customer</a>          
          						<a href="/admin" class="nav-item nav-link">Admin</a>
							</div>
							<div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
								<ul class="navbar-nav text-right">
									
									<li class="nav-item active">
										<a href="{% url 'root:about' %}" class="nav-item nav-link">About Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:contacts' %}" class="nav-item nav-link">Contact Us</a>
									</li>
									<li class="nav-item active">
										<a href="{% url 'root:login' %}">
											<img  id="cart-icon" src="{% static 'root/images/user.png' %}">
										</a>
									</li>
								</ul>
							</div>
				</nav>
{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
		<form method="POST">
			{% csrf_token %}
			{{ form|crispy }}                    
				<div class="form-group"> 
					<div class="col-sm-offset-2 col-sm-10"> 
                            <button type="submit" class="btn btn-success">Submit</button> 
                        </div> 
                    </div>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>
</body>
</html>
